config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foodbanks
  #get 'home/index'
  get 'home/about'
  get 'home/list'
  get 'home/banks'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/foodbank.rb
class Foodbank < ApplicationRecord
	#belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         #has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foodbanks_controller.rb
class FoodbanksController < ApplicationController
  before_action :set_foodbank, only: %i[ show edit update destroy ]

  # GET /foodbanks or /foodbanks.json
  def index
    @foodbanks = Foodbank.all
  end

  # GET /foodbanks/1 or /foodbanks/1.json
  def show
  end

  # GET /foodbanks/new
  def new
    @foodbank = Foodbank.new
  end

  # GET /foodbanks/1/edit
  def edit
  end

  # POST /foodbanks or /foodbanks.json
  def create
    @foodbank = Foodbank.new(foodbank_params)

    respond_to do |format|
      if @foodbank.save
        format.html { redirect_to foodbank_url(@foodbank), notice: "Foodbank was successfully created." }
        format.json { render :show, status: :created, location: @foodbank }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foodbank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodbanks/1 or /foodbanks/1.json
  def update
    respond_to do |format|
      if @foodbank.update(foodbank_params)
        format.html { redirect_to foodbank_url(@foodbank), notice: "Foodbank was successfully updated." }
        format.json { render :show, status: :ok, location: @foodbank }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foodbank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodbanks/1 or /foodbanks/1.json
  def destroy
    @foodbank.destroy

    respond_to do |format|
      format.html { redirect_to foodbanks_url, notice: "Foodbank was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foodbank
      @foodbank = Foodbank.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foodbank_params
      params.require(:foodbank).permit(:name, :address, :city, :state, :zipcode, :email, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index  
  end

  def about
    @about_me = "My Name is Test"
  end

  def banks
    @foodbanks = Foodbank.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foodbanks_helper.rb
module FoodbanksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/foodbanks/_foodbank.html.erb
<div id="<%= dom_id foodbank %>">
  <p>
    <strong>Name:</strong>
    <%= foodbank.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= foodbank.address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= foodbank.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= foodbank.state %>
  </p>

  <p>
    <strong>Zipcode:</strong>
    <%= foodbank.zipcode %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= foodbank.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= foodbank.phone %>
  </p>

</div>

app/views/foodbanks/_form.html.erb
<%= form_with(model: foodbank) do |form| %>
  <% if foodbank.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(foodbank.errors.count, "error") %> prohibited this foodbank from being saved:</h2>

      <ul>
        <% foodbank.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "field mb-3">
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>

  <div class= "field mb-3">
    <%= form.text_field :address, class:"form-control", placeholder:"Address" %>
  </div>

  <div class= "field mb-3">
    <%= form.text_field :city, class:"form-control", placeholder:"City" %>
  </div>

  <div class= "field mb-3">
    <%= form.text_field :state, class:"form-control", placeholder:"State" %>
  </div>

  <div class= "field mb-3">
    <%= form.number_field :zipcode, class:"form-control", placeholder:"Zipcode" %>
  </div>

  <div class= "field mb-3">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class= "field mb-3">
    <%= form.number_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <br>
  
  <div class="actions">
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/foodbanks/edit.html.erb
<h1>Editing foodbank</h1>
<br>
<%= render "form", foodbank: @foodbank %>

<br>

<div>
  <%= link_to "Show", @foodbank, class:"btn btn-secondary" %> 
  <%= link_to "Back", foodbanks_path, class:"btn btn-dark" %>
</div>

app/views/foodbanks/index.html.erb
<table class="table table-striped table-bordered table-hover">
    <thead class="table">
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Zipcode</th>
        <th>Phone</th>
        <th colspan="3"> </th>
      </tr>
    </thead>

    <tbody>
      <% @foodbanks.each do |foodbank| %>
        <tr>
          <td><%= foodbank.name %>
          </td>
          <td><%= foodbank.address %>
          </td>
          <td><%= foodbank.city %>
          </td>
          <td><%= foodbank.state %>
          </td>
          <td><%= foodbank.zipcode %>
          </td>
          <td><%= foodbank.phone %>
          </td>

          <td><%= link_to 'Show', foodbank %></td>
          <td><%= link_to  'Edit', edit_foodbank_path(foodbank) %></td>
          <td><%= link_to 'Destroy', foodbank, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>

        </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to "New foodbank", new_foodbank_path, class:"btn btn-secondary" %>

app/views/foodbanks/new.html.erb
<h1>Add New foodbank</h1>
<br>

<%= render "form", foodbank: @foodbank %>

<br/>
<div>
  <%= link_to "Back", foodbanks_path, class:"btn btn-dark" %>
</div>

app/views/foodbanks/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @foodbank.name %>
  </h1>

  <p class="lead">
    Address: <%= @foodbank.address %> 
    <%= @foodbank.city %> 
    <%= @foodbank.state %> 
    <%= @foodbank.zipcode %> </br>
    Phone: <%= @foodbank.phone %> </br>
    Email: <%= @foodbank.email %>
  </p>
 
  <%= link_to "Edit", edit_foodbank_path(@foodbank), class:"btn btn-secondary" %>
  <%= link_to "Back", foodbanks_path, class:"btn btn-secondary" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

  	<%= link_to 'SC Food Banks', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        	<%= link_to "About", home_about_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Local Foodbanks", home_banks_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Admin Control", foodbanks_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Add", new_foodbank_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link", data: { turbo_method: :delete} %>
          </li>

        <% else %>

          <%# This code is blocked for future implementation 
          <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %DEL>
          </li>
          %>

          <%# Move button to the right %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>

          <% end %>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container">
  <h2>About</h2>
  <p>Welcome to my Ruby on Rails Learning Project!</p>
  <p>My goal is simple: to gain hands-on experience in Ruby on Rails and Bootstrap while building a functional web application.</p>
  <p>This project is my personal learning journey, where I'm exploring the world of web development, from creating dynamic web pages to handling user authentication and beyond.</p>
  <p>Feel free to dive in and explore the codebase! You can clone my repository from GitHub and use it as a valuable resource to learn and practice Ruby on Rails and Bootstrap.</p>
  
  <div class="text-center">
    <a href="https://github.com/mynguy/foodBankApp" class="btn btn-primary">Clone on GitHub</a>
  </div>
</div>

app/views/home/banks.html.erb
<h1>Information on Local Food Banks</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">City</th>
      <th scope="col">State</th>
      <th scope="col">Zipcode</th>
      <th scope="col">Phone</th>
    </tr>
  </thead>
  <tbody>
  	<% @foodbanks.each do |foodbank| %>
      <tr>
	    <td><%= foodbank.name %></td>
	    <td><%= foodbank.address %></td>
	    <td><%= foodbank.city %></td>
	    <td><%= foodbank.state %></td>
	    <td><%= foodbank.zipcode %></td>
	    <td><%= foodbank.phone %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<div class="container">
  <h1>Welcome to the Lowcountry Area Food Bank Database</h1>
  <p>Here, you'll find comprehensive information about all the food banks serving the Lowcountry region.</p>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Food Bank App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>

    <%= render 'home/header' %>  
    <div class ="container">

    <br>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

      <br/>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>